* Overview
This repo contains the code to reproduce the results in "A spectral framework
for measuring diversity in multiple sequence alignments". It essentially
introduce a measure (L_eff) to estimate the diversity (or amount of information)
in multiple sequence alignments. L_eff allows a faithful comparison between
MSAs, as well as generated datasets.

* Content
The code to compute L_eff on MSA is available in ~./package~. The code snippets
to reproduce the figures in the paper are in ~reproducibility.org~. The data to
produce these analyses were extracted from:
- C. Lambert /et al/. (2025) Nat. Commun.
- F. Calvanese /et al/. (2024) NAR
- M. Mirdita /et al/. (2027) NAR

* Install
Requierements: Numpy

#+begin_src bash
cd package
pip install .
#+end_src

* Usage

Compute effective sequence lengths:
#+begin_src python :results output
from eff_len import read_fasta, msa_to_oh, effective_length, cross_effective_length, leff

msa = read_fasta("./package/data/RF00028.fa", seq_type="nuc")

# compute the effective length
msa_oh = msa_to_oh(msa, seq_type="nuc")
N, L, k = msa_oh.shape
L_eff = effective_length(msa_oh)
print(N, L, L_eff, L_eff/L)
#+end_src

#+RESULTS:
: 2611 251 35.88477058938092 0.14296721350350963

A command line tool is also proposed, which works as follows:
#+begin_src bash
# compute the effective length
eff_len package/data/RF00028.fa --stype nuc

# compute the effective length
eff_len package/data/PF00636.25.fa --stype prot
#+end_src

#+RESULTS:

